# Generated by Django 5.2.4 on 2025-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('homepage', models.URLField(blank=True, verbose_name='home page')),
                ('comment', models.TextField(verbose_name='comment')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('is_spam', models.BooleanField(default=False, verbose_name='spam?')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
